
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Start or resume playback
 */
async playbackPlay() : Promise<void> {
    await TAURI_INVOKE("playback_play");
},
/**
 * Pause playback
 */
async playbackPause() : Promise<void> {
    await TAURI_INVOKE("playback_pause");
},
/**
 * Seek to a relative time position
 */
async playbackSeek(time: number) : Promise<void> {
    await TAURI_INVOKE("playback_seek", { time });
},
/**
 * Seek to an absolute time position
 */
async playbackAbsoluteSeek(time: number) : Promise<void> {
    await TAURI_INVOKE("playback_absolute_seek", { time });
},
/**
 * Set playback volume (0.0 - 100.0)
 */
async playbackVolume(volume: number) : Promise<void> {
    await TAURI_INVOKE("playback_volume", { volume });
},
/**
 * Set playback speed
 */
async playbackSpeed(speed: number) : Promise<void> {
    await TAURI_INVOKE("playback_speed", { speed });
},
/**
 * Load a media file URL
 */
async playbackLoad(url: string) : Promise<void> {
    await TAURI_INVOKE("playback_load", { url });
},
/**
 * Change subtitle track
 */
async playbackChangeSubtitle(subtitle: string) : Promise<void> {
    await TAURI_INVOKE("playback_change_subtitle", { subtitle });
},
/**
 * Change audio track
 */
async playbackChangeAudio(audio: string) : Promise<void> {
    await TAURI_INVOKE("playback_change_audio", { audio });
},
/**
 * Clear current playback
 */
async playbackClear() : Promise<void> {
    await TAURI_INVOKE("playback_clear");
},
async toggleTitlebarHide(hide: boolean) : Promise<null> {
    return await TAURI_INVOKE("toggle_titlebar_hide", { hide });
},
/**
 * Toggle fullscreen mode for main window
 */
async toggleFullscreen() : Promise<null> {
    return await TAURI_INVOKE("toggle_fullscreen");
},
/**
 * Show PiP window (makes it visible)
 */
async showPipWindow() : Promise<null> {
    return await TAURI_INVOKE("show_pip_window");
},
/**
 * Hide PiP window (makes it invisible)
 */
async hidePipWindow() : Promise<null> {
    return await TAURI_INVOKE("hide_pip_window");
},
/**
 * Toggle PiP window visibility
 */
async togglePipWindow() : Promise<null> {
    return await TAURI_INVOKE("toggle_pip_window");
},
async getVaultPassword() : Promise<string> {
    return await TAURI_INVOKE("get_vault_password");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
audioChangeEvent: AudioChangeEvent,
audioTrackChange: AudioTrackChange,
bufferingStateChange: BufferingStateChange,
cacheTimeChange: CacheTimeChange,
eofEventChange: EOFEventChange,
errorEventChange: ErrorEventChange,
fileLoadedChange: FileLoadedChange,
pauseForCacheChange: PauseForCacheChange,
playBackStateChange: PlayBackStateChange,
playBackTimeChange: PlayBackTimeChange,
requestAudioEvent: RequestAudioEvent,
requestClearEvent: RequestClearEvent,
requestFileLoad: RequestFileLoad,
requestPlayBackState: RequestPlayBackState,
requestSeekEvent: RequestSeekEvent,
requestSpeedEvent: RequestSpeedEvent,
requestSubtitleEvent: RequestSubtitleEvent,
requestVolumeEvent: RequestVolumeEvent,
speedEventChange: SpeedEventChange,
subtitleChangeEvent: SubtitleChangeEvent,
subtitleTrackChange: SubtitleTrackChange,
volumeEventChange: VolumeEventChange
}>({
audioChangeEvent: "audio-change-event",
audioTrackChange: "audio-track-change",
bufferingStateChange: "buffering-state-change",
cacheTimeChange: "cache-time-change",
eofEventChange: "eof-event-change",
errorEventChange: "error-event-change",
fileLoadedChange: "file-loaded-change",
pauseForCacheChange: "pause-for-cache-change",
playBackStateChange: "play-back-state-change",
playBackTimeChange: "play-back-time-change",
requestAudioEvent: "request-audio-event",
requestClearEvent: "request-clear-event",
requestFileLoad: "request-file-load",
requestPlayBackState: "request-play-back-state",
requestSeekEvent: "request-seek-event",
requestSpeedEvent: "request-speed-event",
requestSubtitleEvent: "request-subtitle-event",
requestVolumeEvent: "request-volume-event",
speedEventChange: "speed-event-change",
subtitleChangeEvent: "subtitle-change-event",
subtitleTrackChange: "subtitle-track-change",
volumeEventChange: "volume-event-change"
})

/** user-defined constants **/



/** user-defined types **/

export type AudioChangeEvent = { index: string }
export type AudioTrackChange = { tracks: Track[] }
export type BufferingStateChange = { buffered: number }
export type CacheTimeChange = { time: number }
export type EOFEventChange = null
export type ErrorEventChange = { message: string }
export type FileLoadedChange = { duration: number; current_time: number }
export type GeneralSettings = { volume: number; playbackSpeed: number; subtitleLanguage: string | null; audioLanguage: string | null; autoPlayNext: boolean; resumePlayback: boolean }
export type PauseForCacheChange = { pause: boolean }
export type PlayBackStateChange = { pause: boolean }
export type PlayBackTimeChange = { position: string }
export type RequestAudioEvent = { index: string }
export type RequestClearEvent = null
export type RequestFileLoad = { url: string; start_time: number | null }
export type RequestPlayBackState = { pause: boolean }
export type RequestSeekEvent = { position: number; absolute: boolean }
export type RequestSpeedEvent = { speed: number }
export type RequestSubtitleEvent = { index: string }
export type RequestVolumeEvent = { percentage: number }
export type SpeedEventChange = { speed: number }
export type SubtitleChangeEvent = { index: string }
export type SubtitleTrackChange = { tracks: Track[] }
export type Track = { id: number; type: string; title?: string | null; lang?: string | null }
export type VolumeEventChange = { percentage: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
