version: 2
updates:
  # Enable version updates for npm (Bun uses npm registry)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "shaik-zeeshan"
    assignees:
      - "shaik-zeeshan"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "shaik-zeeshan"
    assignees:
      - "shaik-zeeshan"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "shaik-zeeshan"
    assignees:
      - "shaik-zeeshan"
    commit-message:
      prefix: "ci"
      include: "scope"
