name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  # Security audit for Rust dependencies
  audit-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: |
          cd src-tauri
          cargo audit

  # Security audit for Node.js dependencies
  audit-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun dependencies
        run: bun install

      - name: Run security audit
        run: bun audit

  # CodeQL analysis
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'rust' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Setup Bun (for JavaScript analysis)
        if: matrix.language == 'javascript'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust (for Rust analysis)
        if: matrix.language == 'rust'
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (JavaScript)
        if: matrix.language == 'javascript'
        run: bun install

      - name: Build (JavaScript)
        if: matrix.language == 'javascript'
        run: bun run build

      - name: Build (Rust)
        if: matrix.language == 'rust'
        run: |
          cd src-tauri
          cargo build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
